services:
  # The App
  - type: web
    name: coupon-management-system
    env: java
    plan: free
    region: ohio
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/coupon-management-system-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: YOUR_MYSQL_DATABASE_URL # Placeholder for external MySQL
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
